### ISSUE TITLE
The NPM package includes a 35 MB file

### ISSUE THREAD

**Issue by chocolateboy** [zuzak/creditor#2]
https://registry.npmjs.org/creditor/-/creditor-1.0.1.tgz

It's a binary file called `creditor`, but I assume it's accidental since it's not referenced anywhere (e.g. it's not invoked by the `index.js` script, which weighs in at just 495 B).

I recommend using the [`files` array](https://docs.npmjs.com/files/package.json#files) in your `package.json` to avoid publishing unintended files.

**Comment by zuzak** [comment]
Thanks!
